### ISSUE TITLE
Is Nitrokey FIDO U2F dead?

### ISSUE THREAD

**Issue by beerisgood** [Nitrokey/nitrokey-fido-u2f-hardware#2]
No news since long time. Looks like you only push the 'Storage' modell

I mean this: https://shop.nitrokey.com/de_DE/shop/product/nitrokey-fido-u2f-20

**Comment by szszszsz** [comment]
Hi! Sorry for the delay. I think you could get answer faster on the support forum, since Github issues are more technical and taken, when time is assigned for given project.
Regarding the question: on the contrary. Development is quite vivid. We are testing new hardware (see https://github.com/Nitrokey/nitrokey-fido-u2f-hardware/pull/1) and firmware changes (https://github.com/Nitrokey/nitrokey-fido-u2f-firmware/pulls). You can add yourself to watchers in both projects to be up-to-date with the latest changes.
